### ISSUE TITLE
[Bug] "Alert Threshold Reached" is visible on the "Map Legend" in "No-Trigger"

### ISSUE THREAD

**Issue by Piotrk39** [rodekruis/IBF-system#1776] opened 2024-11-11 12:56 UTC
### **Who notified us about the bug?**
@Piotrk39 

### **Describe the bug**
When spend IBF-System in No-Trigger mode and user reads the legend "Alert Threshold Reached" is visible.

### **Steps to reproduce**
1. Mock IBF with Floods no-trigger
2. Log-in
3. View "Map Legend"

### **Expected behavior**
"Alert Threshold Reached" should not be visible in "Map Legend"

### Dependencies
TO BE FILLED IN

**Comment by jannisvisser** [comment] 2024-11-11 13:03
@Piotrk39 can you add screenshot or video?

**Comment by jannisvisser** [comment] 2024-11-11 13:22
@arsforza can you confirm if this is actually a bug, or if it's intended? And if it's a bug, is it maybe a one line fix?

**Comment by arsforza** [comment] 2024-11-11 13:25
@jannisvisser I can't confirm if it is a bug or an intended behavior
from a first quick check it seems like `alert_threshold` is passed as `active` (one of the conditions needed to show layers in the legend) even when there is no trigger

**Comment by jannisvisser** [comment] 2024-11-11 13:31
@Piotrk39 I've looked at this and concluded this is a feature, not a bug. Maybe a questionable feature, but so be it. Closing this.

**Closed as completed by jannisvisser** 2024-11-11 13:31 UTC
Labels: bug, wontfix

**Comment by diderikvw** [comment] 2024-11-19 09:05
@BlaiseSelvan  Ping.
